image: node:8

stages:
  - deploy
cache:
  paths:
    - node_modules/ 
    
deploy_production:
  stage: deploy
  tags:
    - career-tinder
  only:
    - tags

  only:
    - code-issue-39-include-gitlab-ci
  script:
    - npm install -g firebase-tools
    - npm install 
    - npm run build 
    - firebase deploy --only hosting --non-interactive --token "$FIREBASE_DEPLOY_KEY" -P "staging-career-tinder"