image: rambabusaravanan/firebase

stages:
  - deploy
cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"
  
deploy_production:
  stage: deploy
  environment: Production
  only:
    - dev
  script:
    - npm install -g firebase-tools
    - npm install 
    - npm run build 
    - firebase use <staging-career-tinder> --token "1/VfIG1b1sQNGflOOEi54rc7OBI5g2A1hQldwYv6JieoA"
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --non-interactive --token "1/VfIG1b1sQNGflOOEi54rc7OBI5g2A1hQldwYv6JieoA"